version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.http.middlewares.shipwrecked-auth.basicauth.users=a:$$2y$$05$$PL44jluNrG4js6rMkjht..3x4BA1eRQxPup4BKZmOxhu1D.zxYrxm"
      - traefik.http.routers.https-0-gwkso00g48gwsk044owcs4gw-app.entryPoints=https, shipwrecked-auth
    ports:
      - 9991:9991
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M 
